using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;

namespace ProcessTSCSCAN
{
    class usb_hid_keybd
    {
    }

    class usb_hid_key
    {
        public uint usage_code { get; set; }
        public string usage_text { get; set; }

        public usb_hid_key(uint usage, string text)
        {
            usage_code = usage;
            usage_text = text;
        }
        static usb_hid_key[] usb_hid_keys ={
                new usb_hid_key(0x00	,	 /*0	*/		"Reserved_(no_event_indicated)"),
                new usb_hid_key(0x01	,	 /*1	*/		"Keyboard_ErrorRollOver"),
                new usb_hid_key(0x02	,	 /*2	*/		"Keyboard_POSTFail"),
                new usb_hid_key(0x03	,	 /*3	*/		"Keyboard_ErrorUndefined"),
                new usb_hid_key(0x04	,	 /*4	*/		"Keyboard_a_and_A"),
                new usb_hid_key(0x05	,	 /*5	*/		"Keyboard_b_and_B"),
                new usb_hid_key(0x06	,	 /*6	*/		"Keyboard_c_and_C"),
                new usb_hid_key(0x07	,	 /*7	*/		"Keyboard_d_and_D"),
                new usb_hid_key(0x08	,	 /*8	*/		"Keyboard_e_and_E"),
                new usb_hid_key(0x09	,	 /*9	*/		"Keyboard_f_and_F"),
                new usb_hid_key(0x0A	,	 /*10	*/		"Keyboard_g_and_G"),
                new usb_hid_key(0x0B	,	 /*11	*/		"Keyboard_h_and_H"),
                new usb_hid_key(0x0C	,	 /*12	*/		"Keyboard_i_and_I"),
                new usb_hid_key(0x0D	,	 /*13	*/		"Keyboard_j_and_J"),
                new usb_hid_key(0x0E	,	 /*14	*/		"Keyboard_k_and_K"),
                new usb_hid_key(0x0F	,	 /*15	*/		"Keyboard_l_and_L"),
                new usb_hid_key(0x10	,	 /*16	*/		"Keyboard_m_and_M"),
                new usb_hid_key(0x11	,	 /*17	*/		"Keyboard_n_and_N"),
                new usb_hid_key(0x12	,	 /*18	*/		"Keyboard_o_and_O"),
                new usb_hid_key(0x13	,	 /*19	*/		"Keyboard_p_and_P"),
                new usb_hid_key(0x14	,	 /*20	*/		"Keyboard_q_and_Q"),
                new usb_hid_key(0x15	,	 /*21	*/		"Keyboard_r_and_R"),
                new usb_hid_key(0x16	,	 /*22	*/		"Keyboard_s_and_S"),
                new usb_hid_key(0x17	,	 /*23	*/		"Keyboard_t_and_T"),
                new usb_hid_key(0x18	,	 /*24	*/		"Keyboard_u_and_U"),
                new usb_hid_key(0x19	,	 /*25	*/		"Keyboard_v_and_V"),
                new usb_hid_key(0x1A	,	 /*26	*/		"Keyboard_w_and_W"),
                new usb_hid_key(0x1B	,	 /*27	*/		"Keyboard_x_and_X"),
                new usb_hid_key(0x1C	,	 /*28	*/		"Keyboard_y_and_Y"),
                new usb_hid_key(0x1D	,	 /*29	*/		"Keyboard_z_and_Z"),
                new usb_hid_key(0x1E	,	 /*30	*/		"Keyboard_1_and_!"),
                new usb_hid_key(0x1F	,	 /*31	*/		"Keyboard_2_and_@"),
                new usb_hid_key(0x20	,	 /*32	*/		"Keyboard_3_and_#"),
                new usb_hid_key(0x21	,	 /*33	*/		"Keyboard_4_and_$"),
                new usb_hid_key(0x22	,	 /*34	*/		"Keyboard_5_and_%"),
                new usb_hid_key(0x23	,	 /*35	*/		"Keyboard_6_and_^"),
                new usb_hid_key(0x24	,	 /*36	*/		"Keyboard_7_and_&"),
                new usb_hid_key(0x25	,	 /*37	*/		"Keyboard_8_and_*"),
                new usb_hid_key(0x26	,	 /*38	*/		"Keyboard_9_and_("),
                new usb_hid_key(0x27	,	 /*39	*/		"Keyboard_0_and_)"),
                new usb_hid_key(0x28	,	 /*40	*/		"Keyboard_Return_(ENTER)"),
                new usb_hid_key(0x29	,	 /*41	*/		"Keyboard_ESCAPE"),
                new usb_hid_key(0x2A	,	 /*42	*/		"Keyboard_DELETE_(Backspace)"),
                new usb_hid_key(0x2B	,	 /*43	*/		"Keyboard_Tab"),
                new usb_hid_key(0x2C	,	 /*44	*/		"Keyboard_Spacebar"),
                new usb_hid_key(0x2D	,	 /*45	*/		"Keyboard_-_and_(underscore)"),
                new usb_hid_key(0x2E	,	 /*46	*/		"Keyboard_=_and_+"),
                new usb_hid_key(0x2F	,	 /*47	*/		"Keyboard_[_and_{"),
                new usb_hid_key(0x30	,	 /*48	*/		"Keyboard_]_and_}"),
                new usb_hid_key(0x31	,	 /*49	*/		"Keyboard_\\_and_|"),
                new usb_hid_key(0x32	,	 /*50	*/		"Keyboard_Non-US_#_and_~"),
                new usb_hid_key(0x33	,	 /*51	*/		"Keyboard_;_and_:"),
                new usb_hid_key(0x34	,	 /*52	*/		"Keyboard_'_and_\""),
                new usb_hid_key(0x35	,	 /*53	*/		"Keyboard_Grave_Accent_and_Tilde"),
                new usb_hid_key(0x36	,	 /*54	*/		"Keyboard,_and_<"),
                new usb_hid_key(0x37	,	 /*55	*/		"Keyboard_._and_>"),
                new usb_hid_key(0x38	,	 /*56	*/		"Keyboard_/_and_?"),
                new usb_hid_key(0x39	,	 /*57	*/		"Keyboard_Caps_Lock"),
                new usb_hid_key(0x3A	,	 /*58	*/		"Keyboard_F1"),
                new usb_hid_key(0x3B	,	 /*59	*/		"Keyboard_F2"),
                new usb_hid_key(0x3C	,	 /*60	*/		"Keyboard_F3"),
                new usb_hid_key(0x3D	,	 /*61	*/		"Keyboard_F4"),
                new usb_hid_key(0x3E	,	 /*62	*/		"Keyboard_F5"),
                new usb_hid_key(0x3F	,	 /*63	*/		"Keyboard_F6"),
                new usb_hid_key(0x40	,	 /*64	*/		"Keyboard_F7"),
                new usb_hid_key(0x41	,	 /*65	*/		"Keyboard_F8"),
                new usb_hid_key(0x42	,	 /*66	*/		"Keyboard_F9"),
                new usb_hid_key(0x43	,	 /*67	*/		"Keyboard_F10"),
                new usb_hid_key(0x44	,	 /*68	*/		"Keyboard_F11"),
                new usb_hid_key(0x45	,	 /*69	*/		"Keyboard_F12"),
                new usb_hid_key(0x46	,	 /*70	*/		"Keyboard_PrintScreen"),
                new usb_hid_key(0x47	,	 /*71	*/		"Keyboard_Scroll_Lock"),
                new usb_hid_key(0x48	,	 /*72	*/		"Keyboard_Pause"),
                new usb_hid_key(0x49	,	 /*73	*/		"Keyboard_Insert"),
                new usb_hid_key(0x4A	,	 /*74	*/		"Keyboard_Home"),
                new usb_hid_key(0x4B	,	 /*75	*/		"Keyboard_PageUp"),
                new usb_hid_key(0x4C	,	 /*76	*/		"Keyboard_Delete_Forward"),
                new usb_hid_key(0x4D	,	 /*77	*/		"Keyboard_End"),
                new usb_hid_key(0x4E	,	 /*78	*/		"Keyboard_PageDown"),
                new usb_hid_key(0x4F	,	 /*79	*/		"Keyboard_RightArrow"),
                new usb_hid_key(0x50	,	 /*80	*/		"Keyboard_LeftArrow"),
                new usb_hid_key(0x51	,	 /*81	*/		"Keyboard_DownArrow"),
                new usb_hid_key(0x52	,	 /*82	*/		"Keyboard_UpArrow"),
                new usb_hid_key(0x53	,	 /*83	*/		"Keypad_Num_Lock_and_Clear"),
                new usb_hid_key(0x54	,	 /*84	*/		"Keypad_/"),
                new usb_hid_key(0x55	,	 /*85	*/		"Keypad_*"),
                new usb_hid_key(0x56	,	 /*86	*/		"Keypad_-"),
                new usb_hid_key(0x57	,	 /*87	*/		"Keypad_+"),
                new usb_hid_key(0x58	,	 /*88	*/		"Keypad_ENTER"),
                new usb_hid_key(0x59	,	 /*89	*/		"Keypad_1_and_End"),
                new usb_hid_key(0x5A	,	 /*90	*/		"Keypad_2_and_Down_Arrow"),
                new usb_hid_key(0x5B	,	 /*91	*/		"Keypad_3_and_PageDn"),
                new usb_hid_key(0x5C	,	 /*92	*/		"Keypad_4_and_Left_Arrow"),
                new usb_hid_key(0x5D	,	 /*93	*/		"Keypad_5"),
                new usb_hid_key(0x5E	,	 /*94	*/		"Keypad_6_and_Right_Arrow"),
                new usb_hid_key(0x5F	,	 /*95	*/		"Keypad_7_and_Home"),
                new usb_hid_key(0x60	,	 /*96	*/		"Keypad_8_and_Up_Arrow"),
                new usb_hid_key(0x61	,	 /*97	*/		"Keypad_9_and_PageUp"),
                new usb_hid_key(0x62	,	 /*98	*/		"Keypad_0_and_Insert"),
                new usb_hid_key(0x63	,	 /*99	*/		"Keypad_._and_Delete"),
                new usb_hid_key(0x64	,	 /*100	*/		"Keyboard_Non-US_\\_and_|"),
                new usb_hid_key(0x65	,	 /*101	*/		"Keyboard_Application"),
                new usb_hid_key(0x66	,	 /*102	*/		"Keyboard_Power"),
                new usb_hid_key(0x67	,	 /*103	*/		"Keypad_="),
                new usb_hid_key(0x68	,	 /*104	*/		"Keyboard_F13"),
                new usb_hid_key(0x69	,	 /*105	*/		"Keyboard_F14"),
                new usb_hid_key(0x6A	,	 /*106	*/		"Keyboard_F15"),
                new usb_hid_key(0x6B	,	 /*107	*/		"Keyboard_F16"),
                new usb_hid_key(0x6C	,	 /*108	*/		"Keyboard_F17"),
                new usb_hid_key(0x6D	,	 /*109	*/		"Keyboard_F18"),
                new usb_hid_key(0x6E	,	 /*110	*/		"Keyboard_F19"),
                new usb_hid_key(0x6F	,	 /*111	*/		"Keyboard_F20"),
                new usb_hid_key(0x70	,	 /*112	*/		"Keyboard_F21"),
                new usb_hid_key(0x71	,	 /*113	*/		"Keyboard_F22"),
                new usb_hid_key(0x72	,	 /*114	*/		"Keyboard_F23"),
                new usb_hid_key(0x73	,	 /*115	*/		"Keyboard_F24"),
                new usb_hid_key(0x74	,	 /*116	*/		"Keyboard_Execute"),
                new usb_hid_key(0x75	,	 /*117	*/		"Keyboard_Help"),
                new usb_hid_key(0x76	,	 /*118	*/		"Keyboard_Menu"),
                new usb_hid_key(0x77	,	 /*119	*/		"Keyboard_Select"),
                new usb_hid_key(0x78	,	 /*120	*/		"Keyboard_Stop"),
                new usb_hid_key(0x79	,	 /*121	*/		"Keyboard_Again"),
                new usb_hid_key(0x7A	,	 /*122	*/		"Keyboard_Undo"),
                new usb_hid_key(0x7B	,	 /*123	*/		"Keyboard_Cut"),
                new usb_hid_key(0x7C	,	 /*124	*/		"Keyboard_Copy"),
                new usb_hid_key(0x7D	,	 /*125	*/		"Keyboard_Paste"),
                new usb_hid_key(0x7E	,	 /*126	*/		"Keyboard_Find"),
                new usb_hid_key(0x7F	,	 /*127	*/		"Keyboard_Mute"),
                new usb_hid_key(0x80	,	 /*128	*/		"Keyboard_Volume_Up"),
                new usb_hid_key(0x81	,	 /*129	*/		"Keyboard_Volume_Down"),
                new usb_hid_key(0x82	,	 /*130	*/		"Keyboard_Locking_Caps_Lock"),
                new usb_hid_key(0x83	,	 /*131	*/		"Keyboard_Locking_Num_Lock"),
                new usb_hid_key(0x84	,	 /*132	*/		"Keyboard_Locking_Scroll_Lock"),
                new usb_hid_key(0x85	,	 /*133	*/		"Keypad_Comma"),
                new usb_hid_key(0x86	,	 /*134	*/		"Keypad_Equal_Sign"),
                new usb_hid_key(0x87	,	 /*135	*/		"Keyboard_International1"),
                new usb_hid_key(0x88	,	 /*136	*/		"Keyboard_International2"),
                new usb_hid_key(0x89	,	 /*137	*/		"Keyboard_International3"),
                new usb_hid_key(0x8A	,	 /*138	*/		"Keyboard_International4"),
                new usb_hid_key(0x8B	,	 /*139	*/		"Keyboard_International5"),
                new usb_hid_key(0x8C	,	 /*140	*/		"Keyboard_International6"),
                new usb_hid_key(0x8D	,	 /*141	*/		"Keyboard_International7"),
                new usb_hid_key(0x8E	,	 /*142	*/		"Keyboard_International8"),
                new usb_hid_key(0x8F	,	 /*143	*/		"Keyboard_International9"),
                new usb_hid_key(0x90	,	 /*144	*/		"Keyboard_LANG1"),
                new usb_hid_key(0x91	,	 /*145	*/		"Keyboard_LANG2"),
                new usb_hid_key(0x92	,	 /*146	*/		"Keyboard_LANG3"),
                new usb_hid_key(0x93	,	 /*147	*/		"Keyboard_LANG4"),
                new usb_hid_key(0x94	,	 /*148	*/		"Keyboard_LANG5"),
                new usb_hid_key(0x95	,	 /*149	*/		"Keyboard_LANG6"),
                new usb_hid_key(0x96	,	 /*150	*/		"Keyboard_LANG7"),
                new usb_hid_key(0x97	,	 /*151	*/		"Keyboard_LANG8"),
                new usb_hid_key(0x98	,	 /*152	*/		"Keyboard_LANG9"),
                new usb_hid_key(0x99	,	 /*153	*/		"Keyboard_Alternate_Erase"),
                new usb_hid_key(0x9A	,	 /*154	*/		"Keyboard_SysReq/Attention"),
                new usb_hid_key(0x9B	,	 /*155	*/		"Keyboard_Cancel"),
                new usb_hid_key(0x9C	,	 /*156	*/		"Keyboard_Clear"),
                new usb_hid_key(0x9D	,	 /*157	*/		"Keyboard_Prior"),
                new usb_hid_key(0x9E	,	 /*158	*/		"Keyboard_Return"),
                new usb_hid_key(0x9F	,	 /*159	*/		"Keyboard_Separator"),
                new usb_hid_key(0xA0	,	 /*160	*/		"Keyboard_Out"),
                new usb_hid_key(0xA1	,	 /*161	*/		"Keyboard_Oper"),
                new usb_hid_key(0xA2	,	 /*162	*/		"Keyboard_Clear/Again"),
                new usb_hid_key(0xA3	,	 /*163	*/		"Keyboard_CrSel/Props"),
                new usb_hid_key(0xA4	,	 /*164	*/		"Keyboard_ExSel"),
                new usb_hid_key(0xE0	,	 /*224	*/		"Keyboard_LeftControl"),
                new usb_hid_key(0xE1	,	 /*225	*/		"Keyboard_LeftShift"),
                new usb_hid_key(0xE2	,	 /*226	*/		"Keyboard_LeftAlt"),
                new usb_hid_key(0xE3	,	 /*227	*/		"Keyboard_Left_GUI"),
                new usb_hid_key(0xE4	,	 /*228	*/		"Keyboard_RightControl"),
                new usb_hid_key(0xE5	,	 /*229	*/		"Keyboard_RightShift"),
                new usb_hid_key(0xE6	,	 /*230	*/		"Keyboard_RightAlt"),
                new usb_hid_key(0xE7	,	 /*231	*/		"Keyboard_Right_GUI"),
        };
    }
}
